### PR TITLE
Ch Restore Deleted Trainee

### PR DESCRIPTION
**Pull request by BenIraa**
**What does this PR do?**

-  It Restore Deleted Trainee
**How can you check it ?**
Use the following code snippet to get a copy of the repository

``git clone https://github.com/atlp-rwanda/atlp-devpulse-bn``

``cd atlp-devpulse-bn``

``git fetch``

``git checkout ch-restoreTrainee``
``npm install``
cp .env.example .env
``npm run dev``

Check repo: https://github.com/atlp-rwanda/atlp-devpulse-fn/compare/ch-restoreTrainee

**What to expect?**
The expectation of this branch is to check on self-trainee details and can Approve or reject it 
Screen Shot 2022-10-27 at 23 27 18

### CODE REVIEW

**Comment by gerard1001** [comment]
Great job, just change that toast message.
You should also use environment variables for for URLs.

**Comment by gerard1001** [comment]
You should also use environment variables for for URLs.

**Comment by BenIraa** [comment]
> Great job, just change that toast message. You should also use environment variables for for URLs.

**Comment by BenIraa** [comment]
> 

Done and thanks!

**Review by gerard1001 — APPROVED** [review]

**Review by istafrica-dennw — APPROVED** [review]

**Pull request merged**
