### PR TITLE
#161: Skeleton Implementation

### LINKED ISSUE #161: Implement Skeleton
Implement a skeleton UI to improve the user experience by displaying placeholder elements during data loading, enhancing perceived performance, and providing visual feedback while content is being fetched.

KEY TASKS:

1. Create lightweight, visually appealing skeleton placeholders for common UI components (e.g., cards, tables, images, buttons, etc.).
2. Ensure the skeleton design matches the layout and spacing of the actual content.
3. Implement the skeleton UI to appear while data is loading across key components of the application (e.g., lists, detailed views, dashboards).
4. Replace skeletons with actual content once the data is fully loaded.
5. Ensure the skeleton UI is lightweight and does not negatively affect the performance of the application.
6. Ensure skeleton UI works well across different screen sizes and devices, maintaining responsiveness and usability.

### PR DESCRIPTION
**Pull request by Ishimwe7**
**Description**
This PR introduces skeleton loading components throughout the application to improve user experience by providing visual feedback during data fetching. These skeleton loaders mimic the structure of the final content, making the interface more intuitive and responsive while the content is loading.

**Description of Task Completed**

- Implemented skeleton loading components across key areas of the application.
- Skeleton loaders are designed to represent the final structure of the content, enhancing the visual feedback to users during loading times.
- Integrated loaders with existing features to ensure a smooth transition when content is being fetched from the backend.

**How to test this PR(locally)**

- Clone the repo and check out the branch ft-skeleton-implementation
- Set up environment variables as indicated in .env.example
- Run npm install followed by npm run dev
- Test loading states in following areas:
     - Navigate through different sections
     - Observe skeleton animations during data fetching
     - Verify smooth transitions between states

**Related Issue**
_https://github.com/atlp-rwanda/atlp-devpulse-fn/issues/161_ 

**Screenshots** 

NavbarMembers

traineeApplicant

editApplicantInfo

trash

### CODE REVIEW

**Review by Ismaelmurekezi — APPROVED** [review]
Nice work @Ishimwe7

**Review by Prince-Kid — APPROVED** [review]
Good Job

**Review by SaddockAime — APPROVED** [review]

**Review by ncutixavier — COMMENTED** [review]
- Remove all changes not related to the skeleton. 
- Please read well the task description, anything not related to your task remove it

**Comment by Ishimwe7** [comment]
> * Remove all changes not related to the skeleton.
> * Please read well the task description, anything not related to your task remove it

done

**Review by ncutixavier — APPROVED** [review]

**Pull request merged**
