### PR TITLE
Ft blogger

### PR DESCRIPTION
**Pull request by Ishimwe7**
**Description**
This PR introduces a blogging feature allowing users to view a list of blogs, select individual blogs for detailed viewing, and interact with them through reactions and comments. This feature is part of our content management system, enhancing user engagement by enabling reactions and discussions on blog posts.

**Tasks Completed:**

-Applicants can create blogs
-Users can view a list of blogs 
-Users can click on individual blogs to read full details.

How to Test it?

Checkout to our branch ft-testing-stages
-Install dependencies: npm install Run the app:npm run dev`
-Log in as an  applicant and you will be redirected to dashboard page
-In the admins panel create an a blog.
-Navigate to blogs and click on add blog

**Applicant:**
Email: [jean@example.com](mailto:jean@example.com)
Password: password123

**Admin:**
Email: [admin@example.com](mailto:admin@example.com)
Password: password123

**Screenshots**

**All Blogs and Add Blog Model**

image

**Single Blog View**

image

image

### CODE REVIEW

**Review by MnorbertVii — CHANGES_REQUESTED** [review]
it seems like the skeleton loader and the modal are misbehaving. i mean i can't be able to interact with the modal to create a new blog.

**Comment by Ishimwe7** [comment]
> Screenshot 2024-11-18 170301 it seems like the skeleton loader and the modal are misbehaving. i mean i can't be able to interact with the modal to create a new blog.

it is now fixed

**Review by MnorbertVii — CHANGES_REQUESTED** [review]
after submitting the form i am not seeing any response. as a result, the blog isn't being successfully created at this time.

**Comment by Ishimwe7** [comment]
> after submitting the form i am not seeing any response. as a result, the blog isn't being successfully created at this time.

it is now fixed

**Review by Ismaelmurekezi — APPROVED** [review]

**Review by Philimuhire — APPROVED** [review]

**Review by Jadowacu1 — APPROVED** [review]

**Review by SaddockAime — APPROVED** [review]

**Pull request merged**
