### PR TITLE
#112 Ft minimize dashboard menu

### PR DESCRIPTION
**Pull request by Prince-Kid**
### PR Description
The `ft-minimize-dashboard-menu` feature allows users to collapse and expand the dashboard sidebar for a streamlined and customizable user interface.

### Description of tasks that were expected to be completed:
- Implement sidebar toggle functionality.
- Ensure the sidebar maintains usability when collapsed (e.g., accessible icons or minimal view).
- Update relevant styles for a better user experience.

### Setup Instructions
1. Clone the repository.
2. Checkout to the `ft-minimize-dashboard-menu` branch.
3. Run `npm install`, then `npm run dev` to verify the app is functioning correctly.
4. Test the sidebar functionality to ensure it collapses and expands as expected.

### Track PR
Issue Number: [#112](https://github.com/atlp-rwanda/atlp-devpulse-fn/issues/112)

### Before
Before Screenshot

### After
After Screenshot 1
After Screenshot 2

### CODE REVIEW

**Review by Ismaelmurekezi — APPROVED** [review]
approved

**Review by Aime-Patrick — COMMENTED** [review]
Why `logout` are in addition while it should be visible not hidden don't you think?

**Review by mugishaj092 — DISMISSED** [review]
Add some icons by refering to figma design

**Review by tysepa — COMMENTED** [review]
looks good

**Review by tysepa — APPROVED** [review]

**Review by Aime-Patrick — APPROVED** [review]

**Comment by ncutixavier** [comment]
@Prince-Kid  Please write a clear PR description

**Comment by Aime-Patrick** [comment]
Everything are breaking `padding` ,`margin` ,`pages` ,`alignment`

**Comment by Aime-Patrick** [comment]
Everything are breaking `padding` ,`margin` ,`pages` ,`alignment`

**Pull request closed without merging**
