### PR TITLE
Update Trainee Applicant Status FN

### PR DESCRIPTION
**Pull request by un-anelka**
**What does this PR do?**
Allows users/admins to update the trainee applicant's status either passed, relegated, or failed.

**Description of this PR**
This PR aims to achieve assigning trainee applicant's status so as to allow admins to perform different actions based on the set status mentioned above.

**How should this be manually tested?**

- Run git clone https://github.com/atlp-rwanda/atlp-devpulse-fn to clone the project 
- Run cd atlp-devpulse-bn to go to the root project
- Run git checkout ft-status-update-bn
- Run npm i or npm install to install all needed dependencies.
- Run npm run dev to start the server.
- Navigate to filter trainee page and tests the functionalities.

**Note**
The default status in `Not Assigned` that comes during applicant creation.

**What to expect?**
Check the following attachments:
Assignment_Mobile
Assignment

### CODE REVIEW

**Review by PrinceNiyonshuti — APPROVED** [review]
Looks Good

**Review by Gedeonir — COMMENTED** [review]
look good to me but try to not console data in the console

**Review by gerard1001 — CHANGES_REQUESTED** [review]
@un-anelka, I can't find the backend branch for this task. There is no " ft-status-update-bn".
I think that is why I am getting this error on the frontend.
Screen Shot 2022-11-24 at 11 24 21

**Comment by un-anelka** [comment]
> @un-anelka, I can't find the backend branch for this task. There is no " ft-status-update-bn". I think that is why I am getting this error on the frontend. Screen Shot 2022-11-24 at 11 24 21

The backend for it was merged, please pull the latest changes on develop and review again

**Comment by un-anelka** [comment]
> > @un-anelka, I can't find the backend branch for this task. There is no " ft-status-update-bn". I think that is why I am getting this error on the frontend. Screen Shot 2022-11-24 at 11 24 21
> 
> The backend for it was merged, please pull the latest changes on develop and review again @gerard1001

**Pull request merged**
