### PR TITLE
Ft schedule tech interview

### PR DESCRIPTION
**Pull request by bahati10**
### PR Description

This PR allows the admin to invite a trainee applicant to the technical interview
by sending emails to both the applicant and interview coordinator

### Description of tasks that were expected to be completed

As a trainee applicant, I will receive an email with a meeting link for the interview invitation.
As an admin, I should be able to create, view, and update the status of the interview

### How can this be tested?
- Clone repo
- Checkout branch [here](ft-schedule-technical-interview)
- Make sure that you set the environment variables referring to `.env.example`
- Run `npm install`, then `npm run dev` to check if the app is running successfully
- Use Apollo server and interact with doc resolvers

### Track PR (issue number & link)
Issue: [#208](https://github.com/atlp-rwanda/atlp-devpulse-fn/issues/208)

### Screenshots (If appropriate especially on the frontend)
Screenshot 2024-12-02 at 03 14 10
Screenshot 2024-12-02 at 03 14 57
Screenshot 2024-12-02 at 03 15 55

N/A

### CODE REVIEW

**Review by iChris-tian — APPROVED** [review]

**Review by MUNYESHURImanzi — APPROVED** [review]

**Review by Mugisha146 — CHANGES_REQUESTED** [review]
I tested this Frontend PR with your backend and find this issue:
1. duplication on invite button
Screenshot 2024-12-03 at 08 17 03
2. On Invite you must add when to do interview means date and time 
Screenshot 2024-12-03 at 08 17 13
3. On your PR application stage history not displayed
Screenshot 2024-12-03 at 08 19 32
4. nothing is displayed on Interview schedule on applicant side
Screenshot 2024-12-03 at 08 19 45
5. check well if email is being sent because am able to see notification only not getting email

**Comment by bahati10** [comment]
@Mugisha146 Thank you for mentioning these issues

1. The issue is fixed, the duplicate has been removed
2. The feature is from the previous merged task and is under fix too
3. Stage history under fix too
4. This is a different context for the interview, The only close thing an applicant can see is 
their details on my applicants page
5. Could you provide the screenshot again, please?

**Comment by Mugisha146** [comment]
Great, all issues are resolved.

**Review by Mugisha146 — APPROVED** [review]
Great Job

**Pull request merged**
