### PR TITLE
Ft Documentations Frontend

### PR DESCRIPTION
**Pull request by SHYAKA-Aime**
### PR Description

This PR allows admin to create, update, view and delete docs. 

### Description of tasks that were expected to be completed

As an applicant I can view the documents on the docs page. 
As an admin I should be able to create, view, update and delete the documents on docs page

### How can this been tested?
- Clone repo
- Checkout branch `ft-documentation-fn`
- Make sure that you set the environment variables referring to `.env.example`
- Run `npm install`, then `npm run dev` to check if the app is running successfully
- Use apolo server and interact with doc resolvers

### Track PR (issue number & link)
Issue: [#250](https://github.com/atlp-rwanda/atlp-devpulse-fn/issues/250)

### Screenshots (If appropriate especially on the frontend)
N/A

### CODE REVIEW

**Review by MUNYESHURImanzi — APPROVED** [review]

**Review by vegetason — APPROVED** [review]
This works well

**Comment by Salim-54** [comment]
image

Make sure the pop-up is centered and the fields are of equal width
and remember to rebase

**Comment by SHYAKA-Aime** [comment]
> image
> Make sure the pop-up is centered and the fields are of equal width and remember to rebase


The above issue is now fixed @Salim-54 
Screenshot (63)

**Comment by SHYAKA-Aime** [comment]
> Make sure the pop-up is centered and the fields are of equal width and remember to rebase

This issue is now solved @Salim-54 
Screenshot (64)

**Review by berniceu — APPROVED** [review]

**Review by iChris-tian — APPROVED** [review]

**Pull request merged**
