### PR TITLE
#103 Fixed navigation routing

### PR DESCRIPTION
**Pull request by Aime-Patrick**
# Description
Navigation seems to be broken.

## How to reproduce
1. Login
2. Click on Help (this returns the current page with `help` slug added to the route
3. Click on another page say, calendar. `/calendar` will be appended to `.../help`

# Description of tasks that were expected to be completed

-  Fixed login redirection after successful 
-  Fixed appending route to look like this `/calendar` instead of `../help/calendar`
-  we have created a layout for `applicant` and `admin` and isolated routes based on the role for improved efficiency.
- The default value for the applicant is `applicant`, and for the admin is `admin`. eg(`../applicant`) and eg(`../admin`)

# How has this been tested?

- Switch to this branch "fx-navigation"
- Manually test by clicking through all dashboard menus.

# Deployed Test

- In the Vercel bot click on `Visit preview` you will be directed to the website
- Create an account if you don't have one, then log in.
- Navigation through dashboard menus to test `navigation route`

# Screenshots
## Dashboard Page
Screenshot 2024-09-13 124945

## Before fixing navigation
Screenshot 2024-09-13 143412

## After Fixed navigation
Screenshot 2024-09-13 125139

## Applicant side
image

### CODE REVIEW

**Review by ndahimana154 — APPROVED** [review]
Well done @Aime-Patrick

**Review by ManziPatrick — APPROVED** [review]

**Review by SHYAKA-Aime — APPROVED** [review]

**Comment by ncutixavier** [comment]
How this should be tested with deployed link? @Aime-Patrick

**Review by vegetason — APPROVED** [review]
well done on this task

**Review by berniceu — APPROVED** [review]

**Comment by Aime-Patrick** [comment]
> How this should be tested with deployed link? @Aime-Patrick

Check the Description of this pull request @ncutixavier

**Review by ncutixavier — APPROVED** [review]

**Pull request merged**
