### PR TITLE
#285 An author will be able to update a blog

### LINKED ISSUE #285: author update blog
Author update blog post implementation

### PR DESCRIPTION
**Pull request by mutsinziisaac**
### PR Description

This PR adds functionality to allow users to update their blogs and modifies the relevant files to support this feature.

### Description of tasks that were expected to be completed

1. Implement the ability for users to update their own blogs.
2. Adde richtext as the content input for both create and update of the blog.
3. Ensure proper validation and authorization checks to prevent unauthorized edits.
4. Previously, there was a vague option for users to update their blogs, leading to challenges in maintaining or correcting their content
5. blogs are hidden by default, so only admin can unhide them.

### How has this been tested?

Clone the repository.
Checkout the branch ft-updateblog.
Set up the environment variables as indicated in .env.example.
Run npm install followed by npm run dev to start the app.
Test the update functionality on the blog on apollo studio.

### Deployed Link:
https://atlp-devpulse-fn-git-ft-updateblogs-devpulses-projects-62c56cf1.vercel.app/

### Track PR (Issue number & link):

#285 

### ScreenShoot

Screenshot 2024-12-04 at 17 57 30

### CODE REVIEW

**Review by Mugisha146 — APPROVED** [review]

**Review by Ismaelmurekezi — APPROVED** [review]

**Review by Jadowacu1 — APPROVED** [review]

**Comment by ncutixavier** [comment]
why do you have delete commits in this PR?

**Review by Mugisha146 — APPROVED** [review]

**Review by Prince-Kid — APPROVED** [review]
Great Job @mutsinziisaac

**Review by SaddockAime — APPROVED** [review]

**Comment by ncutixavier** [comment]
- You included someones commits, and if it's not going to be resolved, your PR can't be merged
- Only way to fix this, Make sure that your PR has only changes you made

**Comment by Mugisha146** [comment]
> * You included someones commits, and if it's not going to be resolved, your PR can't be merged
> * Only way to fix this, Make sure that your PR has only changes you made

He did not include someones commit due to PC issues he was having. We met, used my PC to fix the requested changes, and committed them. Please review the code and test it. Everything is fine.

**Review by ncutixavier — APPROVED** [review]

**Pull request merged**
