### PR TITLE
Have a user be able to apply as a trainee

### PR DESCRIPTION
**Pull request by robsdagreat**
PR Description
Have a user being able to apply for becoming a trainee with basic data and then afterwards he/she can fill the additional information( additional attributes)

Description of tasks that were expected to be completed
A user has to be able to apply for becoming a trainee , provide the additional information required for a trainee and then the application is ready to be considered.

Functionality
After logging in navigate to my applicaiton, then click on Become a trainee button, and fill the form. After successfully submitting the application, you will be prompted to fill the rest of the information so that your application can be considered.

How has this been tested?
This was tested using apollo server
On the Preview link you can login as superAdmin 
email: admin@example.com
password: password123
 
Track PR
https://github.com/atlp-rwanda/atlp-devpulse-fn/issues/156

Screenshots (If appropriate)

updated3png

Updated2

Front1

Front2

Front3

### CODE REVIEW

**Review by Philimuhire — APPROVED** [review]

**Review by Mugisha146 — CHANGES_REQUESTED** [review]
1.Work on light mode for all your page
Screenshot 2024-10-07 at 11 26 47
2. Send Application must done by the one who logged in  and can be better if you click on became trainee  then name and email be fetched without refill it again

**Review by mugishaj092 — CHANGES_REQUESTED** [review]
Work on feedback @Mugisha146 give you and fix the checks

**Comment by robsdagreat** [comment]
All the changes required well implemented 

Light1
light2

**Review by mugishaj092 — APPROVED** [review]

**Review by mutsinziisaac — APPROVED** [review]

**Review by Mugisha146 — APPROVED** [review]
Great Job

**Review by SaddockAime — APPROVED** [review]

**Pull request closed without merging**
