### PR TITLE
Clear Trash

### PR DESCRIPTION
**Pull request by un-anelka**
## What does this PR do?

Clear Trash (Permanent delete of soft-deleted trainees)

## Description of Task to be completed?

1. Emptying Trash (Recyclebin)

## How should this be manually tested?

- `Clone the repo`
- checkout` to branch `ft-clear-recylebin` by running git checkout ft-clear-recylebin
- Install packages, run npm i or  run npm install
- Run server and app
- Go http://localhost:3000/trash, a list of soft deleted trainees will appear

Click `Empty Trash` button and observer the results.

### CODE REVIEW

**Review by tysepa — APPROVED** [review]
so good

**Review by UmuhireJessie — CHANGES_REQUESTED** [review]
Good job!

- Not sure why this pen icon
image

**Comment by un-anelka** [comment]
> 

The pen is opened because that this the screen, I wanted to show, otherwise, no other reason behind that @UmuhireJessie

**Comment by UmuhireJessie** [comment]
> > 
> 
> The pen is opened because that this the screen, I wanted to show, otherwise, no other reason behind that @UmuhireJessie

pen or pencil icon is mostly used on edit functions, you might consider using a restore icon instead

**Comment by un-anelka** [comment]
> > > 
> > 
> > 
> > The pen is opened because that this the screen, I wanted to show, otherwise, no other reason behind that @UmuhireJessie
> 
> pen or pencil icon is mostly used on edit functions, you might consider using a restore icon instead

> Good idea, though this was not part of my tasks, I can look into that.

**Review by UmuhireJessie — APPROVED** [review]
Good work!

**Pull request merged**
