### PR TITLE
Ch Adding tailwind to the project:

### PR DESCRIPTION
**Pull request by Niyonkuru1**
## What does this PR do?

Adding and configuring tailwind. 
Css command should be given through tailwind

## Description of Task to be completed?

Using the tailwind in the project

## How should this be manually tested?

- `Clone the repo`

- `checkout` to branch `ch-add-tailwind-to-the-project`

- Pull the changes by `git pull`

- Install all packages by running `npm install`

- Start app by `running npm run dev`

- You should see the styled component using `tailwind`.

## Any background context you want to provide?

N/A

## What are the relevant pivotal tracker stories?

[Trello Board reference](https://trello.com/c/mq7DwMn6/46-add-tailwind-css-to-the-project-and-configure-it)

### CODE REVIEW

**Review by arthurjunior250 — CHANGES_REQUESTED** [review]
Good job, but fix the Circle-ci issues

**Comment by Niyonkuru1** [comment]
> Good job, but fix the Circle-ci issues

Yeah I will take care of it,
Thank you.

**Review by tysepa — APPROVED** [review]
please check your test and make sure that your blanch the build is working

**Comment by Niyonkuru1** [comment]
> please check your test and make sure that your blanch the build is working

thank you 
I have done it

**Review by Hodal66 — APPROVED** [review]

**Review by Hodal66 — APPROVED** [review]

**Review by UmuhireJessie — APPROVED** [review]

**Pull request merged**
