### PR TITLE
View single trainee details

### PR DESCRIPTION
**Pull request by tysepa**
Screen Shot 2022-10-31 at 20 23 38
**What does this PR do?**

-  It displays all information of a single Trainee  in details

**How can you check it ?**
Use the following code snippet to get a copy of the repository

``git clone https://github.com/atlp-rwanda/atlp-devpulse-bn``

``cd atlp-devpulse-bn``

``git fetch``

``git checkout view-single-trainee-details``
``npm install``
cp .env.example .env
``npm run dev``

Check repo: https://github.com/atlp-rwanda/atlp-devpulse-fn/compare/view-single-trainee-details

**What to expect?**
The expectation of this branch is to check on self-trainee details and can Approve or reject it

### CODE REVIEW

**Review by Pniyonshuti — APPROVED** [review]
LGTM

**Review by UmuhireJessie — CHANGES_REQUESTED** [review]
Good job on the design. Please consider a few things

- First, Please resolve conflicts and test every thing. They should be working
- Add a margin button on the Actions div
image
- On this page, click on view, redirect to your page `/trainee-details`, and grab the `id` of a trainee which will be shown in URL. Ex: `http://localhost:3000/trainee-details/861035783245`
image
- Not sure why, but the trainee info is not shown
image

**Review by istafrica-dennw — CHANGES_REQUESTED** [review]
Epa, waht happens when you refresh the page?
i remember last time i requested you to include the user id in the url

**Comment by tysepa** [comment]
> Epa, waht happens when you refresh the page? i remember last time i requested you to include the user id in the url

In the time refresh page, it returns to that same page and the same id 
About adding the user id in the URL it included

**Review by Gedeonir — CHANGES_REQUESTED** [review]
Please squash the commits into one commit

**Pull request merged**
