### PR TITLE
Forget password   #147

### LINKED ISSUE #146: Forgot passowrd
Implement a secure and user-friendly "Forgot Password" feature that allows users to reset their passwords if they forget them.

Key tasks:

1. Make a "Forgot Password?" link on the login page to direct users to the password reset request page.
2. Generate a unique, time-limited password reset token and send it to the user’s registered email address with instructions for resetting their password.
3. Ensure that the email includes a secure link to the password reset page.

### PR DESCRIPTION
**Pull request by ManziPatrick**
### **PR Description**

The "**Forgot Password"** page allows users to easily request a password reset by entering their registered email address. After submission, an email with a secure link will be sent to the user. Clicking the link will take them to the reset password page, where they can enter a new password using a token from the email.

### Forget password image

image

### Reset password email
image

### Reset password
image

### CODE REVIEW

**Review by Aime-Patrick — APPROVED** [review]

**Review by iChris-tian — APPROVED** [review]

**Review by vegetason — APPROVED** [review]
well done on this task

**Review by SHYAKA-Aime — APPROVED** [review]

**Review by berniceu — COMMENTED** [review]
Change this error message for when user does not exist

Screenshot 2024-10-07 203631

**Comment by ManziPatrick** [comment]
> Change this error message for when user does not exist
> 
> Screenshot 2024-10-07 203631

you        have to be connected to backend 
image

**Review by Aime-Patrick — APPROVED** [review]

**Review by berniceu — APPROVED** [review]

**Review by tysepa — COMMENTED** [review]
work good

**Pull request merged**
