### PR TITLE
Ft recollect single trainee details

### PR DESCRIPTION
**Pull request by tysepa**
**What does this PR do?**

this PR show all information and  the details of the trainee and Application cycles

**Description of Task to be completed?**

Trainee_id is required to view all the trainee details and information
All trainees are in the table you can access it and check their cycle
Also Has dark mode and right mode

**How should this be manually tested?**

Clone the [repo](https://github.com/atlp-rwanda/atlp-devpulse-fn/ft-recollect-single-trainee-details)

checkout to branch ft-recollect-single-trainee-details

Install all the required packages by running `npm install `
Screen Shot 2022-11-22 at 20 28 46

Start the app by running `npm run dev`

**_All mode_**

### CODE REVIEW

**Review by Gedeonir — CHANGES_REQUESTED** [review]
Try to make applicant information to render after fetching data as you did on applicant info
and remove white space at the bottom in dark mode

Capture

**Review by Gedeonir — CHANGES_REQUESTED** [review]
Try to make applicant information to render after fetching data as you did on applicant info
and remove white space at the bottom in dark mode

Capture

**Comment by tysepa** [comment]
> Try to make applicant information to render after fetching data as you did on applicant info and remove white space at the bottom in dark mode
> 
> Capture

the reason's why that page can be open because it gets the Id from that table of trainees and it uses that URL on the link

**Comment by Gedeonir** [comment]
But we can have something which is being displayed while querry is loading instead of undefined

**Review by PrinceNiyonshuti — APPROVED** [review]
Looks good to me

**Pull request closed without merging**
